### ISSUE TITLE
Crash when switching to a new movie

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#11]
After completing the "Eyes" tutorial I moved on to "Colloids" by opening `colloids.mp4`. The GUI crashed with this traceback (perhaps because I had "Use part processed" still enabled?):

```
File /Users/nkeim/projects/joss-reviews/testdata/colloids.hdf5 does not exist
Error in DataStore.load
Postprocessing:   0%|                                                                                                 | 0/1 [00:00<?, ?it/s]
Error in general.dataframes
'DataStore' object has no attribute 'df'
Error in DataStore.save
Traceback (most recent call last):
  File "/Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/site-packages/particletracker/gui/main_gui.py", line 246, in <lambda>
    self.frame_selector.rangeChanged.connect(lambda x: self.param_change(x))
  File "/Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/site-packages/particletracker/gui/main_gui.py", line 340, in param_change
    self.update_viewer()
  File "/Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/site-packages/particletracker/gui/main_gui.py", line 391, in update_viewer
    annotated_img, proc_img = self.tracker.process_frame(frame_number, use_part=True)
  File "/Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/site-packages/particletracker/project/__init__.py", line 148, in process_frame
    self.pp.process(f_index=frame_num, use_part=use_part)
  File "/Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/site-packages/particletracker/postprocess/__init__.py", line 42, in process
    data.df = getattr(pm, method_name)(data.df, f_index=f,parameters=self.parameters, call_num=call_num)
AttributeError: 'DataStore' object has no attribute 'df'
zsh: abort      python
(particle) chou: /Users/nkeim/opt/anaconda3/envs/particle/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
I'll look into this

**Comment by mikesmithlab** [comment]
Looking at the error message and reading your comment the issue is this. Use_part_processed assumes you have already run the limited processing to create a videoname.hdf5 It then uses this datafile to run the postprocessing. So when you did the Eyes tutorial you created a eyes.hdf5 file. When you then opened colloids.mp4 the use_part_processed button means that the software immediately tried to access colloids.hdf5 to run a postprocessing command. The file doesn't exist though. Hence it crashes the software. I could perhaps make sure that when you open a movie it resets this use_part_processed toggle button which would then avoid this.

**Comment by nkeim** [comment]
That makes sense. Yes, I agree that it's worthwhile to check and at least display an error dialog.
