### ISSUE TITLE
the `img sequence` option is not implemented

### ISSUE THREAD

**Issue by alexlib** [MikeSmithLabTeam/particletracker#2]
https://github.com/MikeSmithLabTeam/particletracker/blob/8b631e0d851146efa78885e114fa2baa0deb346f/particletracker/gui/main_gui.py#L103

the GUI opens with the options to choose only movies, `mp4`, `avi`, etc. no image extensions or instructions on how to choose an image sequence are given 
https://github.com/openjournals/joss-reviews/issues/3611

**Comment by mikesmithlab** [comment]
Not sure why this says Img Sequence. The image reading works through OpenCV and our intention was always to read from movies since this is what people record via a camera. Img Sequence might be a future addition but it is not something we intended to implement at this point. I will update the code to remove this confusion.
