### ISSUE TITLE
Preprocessed image doesn't work when "Use part processed" is turned on

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#9]
Clicking "Captured image" to view the preprocessed image does nothing when "Use part processed" is turned on. This is confusing to a new user — perhaps an error message, or graying out the button, would help.

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
Hi thanks for this.  This is by design. ie Preprocessed image shouldn't work when use part processed is turned on. The reason is that "use part proccesed" is no longer running the first 5 steps (including preprocessing) but is taking data from the already processed dataframe stored in videoname.hdf5 and then allowing you to interact with this via postprocessing and annotation. This is not only a way of speeding things up (ie you don't need to keep reprocessing things if they are working) but also necessary if you want to use a method (such as plotting a trajectory) that requires data from multiple frames. We disable the preprocess button so that people don't mistakenly think they are altering the preprocessing and wonder why nothing is happening. This is also indicated by the fact that the first 5 tabs should become greyed out when you select "use part processed". Hopefully that makes sense.
